import manali from "@/assets/trip-manali.jpg";
import spiti from "@/assets/trip-spiti.jpg";
import bali from "@/assets/trip-bali.jpg";
import kashmir from "@/assets/trip-kashmir.jpg";
import meghalaya from "@/assets/trip-meghalaya.jpg";
import ladakh from "@/assets/trip-ladakh.jpg";
import thailand from "@/assets/trip-thailand.jpg";
import goa from "@/assets/trip-goa.jpg";

export type TripCategory = "weekend" | "backpacking";

export interface Departure {
  date: string;
  spotsLeft: number;
}

export interface Trip {
  slug: string;
  title: string;
  location: string;
  country: string;
  image: string;
  gallery: string[];
  durationDays: number;
  durationNights: number;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  groupSize: string;
  difficulty: "Easy" | "Moderate" | "Challenging";
  category: TripCategory;
  departureCities: string[];
  pickup: string;
  drop: string;
  months: string[];
  tagline: string;
  description: string;
  highlights: string[];
  inclusions: string[];
  exclusions: string[];
  itinerary: { day: number; title: string; details: string }[];
  departures: Departure[];
}

export const trips: Trip[] = [
  // WEEKEND TRIPS (14)
  {
    slug: "gokarna-dandeli",
    title: "Gokarna & Dandeli Weekend",
    location: "Karnataka",
    country: "India",
    image: goa,
    gallery: [goa, bali, meghalaya],
    durationDays: 3,
    durationNights: 2,
    price: 5999,
    rating: 4.7,
    reviews: 456,
    groupSize: "15–25",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Bangalore", "Goa"],
    pickup: "Gokarna Beach",
    drop: "Gokarna Beach",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Beach vibes & river adventures",
    description: "A perfect blend of serene beaches in Gokarna and thrilling water sports in Dandeli.",
    highlights: ["Gokarna beach walks", "Dandeli river rafting", "Local beach shacks", "Sunset viewpoints"],
    inclusions: ["2 nights stay", "Breakfast & dinner", "All transfers", "Activity entries"],
    exclusions: ["Lunch", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Arrival in Gokarna", details: "Check-in & beach exploration." },
      { day: 2, title: "Dandeli adventure", details: "River rafting & local sightseeing." },
      { day: 3, title: "Departure", details: "Beach time & departure." },
    ],
    departures: [
      { date: "15 May 2026", spotsLeft: 8 },
      { date: "22 May 2026", spotsLeft: 12 },
    ],
  },
  {
    slug: "gokarna-jogfalls",
    title: "Gokarna & Jog Falls Weekend",
    location: "Karnataka",
    country: "India",
    image: goa,
    gallery: [goa, bali, meghalaya],
    durationDays: 3,
    durationNights: 2,
    price: 6599,
    rating: 4.8,
    reviews: 389,
    groupSize: "12–20",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Bangalore", "Goa"],
    pickup: "Gokarna",
    drop: "Jog Falls",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb"],
    tagline: "Waterfalls & coastal charm",
    description: "Experience pristine beaches and India's second-highest waterfall in one thrilling trip.",
    highlights: ["Gokarna beaches", "Jog Falls viewing", "Waterfall trek", "Scenic viewpoints"],
    inclusions: ["2 nights stay", "All meals", "Local guide", "Transfers"],
    exclusions: ["Personal activities"],
    itinerary: [
      { day: 1, title: "Gokarna arrival", details: "Beach settlement & local exploration." },
      { day: 2, title: "Jog Falls drive", details: "Waterfall viewing & trek." },
      { day: 3, title: "Departure", details: "Scenic drives & final viewpoints." },
    ],
    departures: [
      { date: "16 May 2026", spotsLeft: 10 },
      { date: "30 May 2026", spotsLeft: 14 },
    ],
  },
  {
    slug: "wayanad",
    title: "Wayanad Hill Station Weekend",
    location: "Kerala",
    country: "India",
    image: meghalaya,
    gallery: [meghalaya, kashmir, spiti],
    durationDays: 3,
    durationNights: 2,
    price: 7999,
    rating: 4.8,
    reviews: 523,
    groupSize: "12–20",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Bangalore", "Mysore"],
    pickup: "Wayanad",
    drop: "Wayanad",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb"],
    tagline: "Lush greens & spice plantations",
    description: "Explore the green valleys of Wayanad with spice plantation tours and scenic trekking.",
    highlights: ["Spice plantation tour", "Pookode lake", "Chembra peak trek", "Local homestay"],
    inclusions: ["2 nights stay", "All meals", "Guided tours", "Transfers"],
    exclusions: ["Personal activities", "Tips"],
    itinerary: [
      { day: 1, title: "Wayanad arrival", details: "Check-in & orientation." },
      { day: 2, title: "Plantation & lake", details: "Spice tour & Pookode lake." },
      { day: 3, title: "Departure", details: "Morning trek & drop." },
    ],
    departures: [
      { date: "08 Jun 2026", spotsLeft: 6 },
      { date: "15 Jun 2026", spotsLeft: 10 },
    ],
  },
  {
    slug: "ooty-coonoor",
    title: "Ooty & Coonoor Weekend",
    location: "Tamil Nadu",
    country: "India",
    image: ladakh,
    gallery: [ladakh, meghalaya, manali],
    durationDays: 3,
    durationNights: 2,
    price: 7499,
    rating: 4.6,
    reviews: 612,
    groupSize: "15–25",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Bangalore", "Coimbatore"],
    pickup: "Ooty",
    drop: "Ooty",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Queen of the hills & toy trains",
    description: "Classic hill station experience with toy train ride, botanical gardens, and scenic viewpoints.",
    highlights: ["Toy train ride", "Botanical gardens", "Doddabetta peak", "Coonoor tea plantations"],
    inclusions: ["2 nights stay", "Breakfast & dinner", "Train ride", "Transfers"],
    exclusions: ["Personal expenses"],
    itinerary: [
      { day: 1, title: "Ooty arrival", details: "Hotel check-in & local exploration." },
      { day: 2, title: "Toy train & gardens", details: "Nilgiri mountain railway & botanical gardens." },
      { day: 3, title: "Coonoor day trip", details: "Tea estates & departure." },
    ],
    departures: [
      { date: "10 May 2026", spotsLeft: 10 },
      { date: "24 May 2026", spotsLeft: 15 },
    ],
  },
  {
    slug: "isha-ooty",
    title: "Isha & Ooty Spiritual Retreat",
    location: "Tamil Nadu",
    country: "India",
    image: manali,
    gallery: [manali, meghalaya, ladakh],
    durationDays: 4,
    durationNights: 3,
    price: 7499,
    rating: 4.9,
    reviews: 389,
    groupSize: "10–20",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Bangalore", "Coimbatore"],
    pickup: "Isha Foundation",
    drop: "Isha Foundation",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb"],
    tagline: "Spiritual journey & mountain retreat",
    description: "Combine Isha Foundation's spiritual programs with Ooty's natural beauty.",
    highlights: ["Isha meditation", "Ooty hill views", "Nature walks", "Spiritual sessions"],
    inclusions: ["3 nights stay", "All meals", "Programs & activities", "Transfers"],
    exclusions: ["Personal meditation items"],
    itinerary: [
      { day: 1, title: "Isha arrival", details: "Program orientation & settling." },
      { day: 2, title: "Isha programs", details: "Meditation & wellness sessions." },
      { day: 3, title: "Ooty day trip", details: "Hill station exploration." },
      { day: 4, title: "Departure", details: "Final sessions & drop." },
    ],
    departures: [
      { date: "12 Jun 2026", spotsLeft: 8 },
      { date: "26 Jun 2026", spotsLeft: 12 },
    ],
  },
  {
    slug: "coorg-chikmagalur",
    title: "Coorg & Chikmagalur Coffee Trail",
    location: "Karnataka",
    country: "India",
    image: bali,
    gallery: [bali, meghalaya, kashmir],
    durationDays: 3,
    durationNights: 2,
    price: 6499,
    rating: 4.7,
    reviews: 478,
    groupSize: "12–18",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Bangalore", "Mangalore"],
    pickup: "Coorg",
    drop: "Coorg",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Coffee plantations & misty mountains",
    description: "Explore India's coffee capital with plantation tours, waterfalls, and scenic trails.",
    highlights: ["Coffee plantation tours", "Abbey Falls", "Bheemesswara Falls", "Local homestays"],
    inclusions: ["2 nights stay", "Breakfast & dinner", "Guided tours", "Transfers"],
    exclusions: ["Lunch", "Personal items"],
    itinerary: [
      { day: 1, title: "Coorg arrival", details: "Hotel check-in & local walk." },
      { day: 2, title: "Coffee tours & falls", details: "Plantation visit & waterfall exploration." },
      { day: 3, title: "Chikmagalur extension", details: "Tea estates & departure." },
    ],
    departures: [
      { date: "05 May 2026", spotsLeft: 7 },
      { date: "19 May 2026", spotsLeft: 11 },
    ],
  },
  {
    slug: "araku",
    title: "Araku Valley Hill Station",
    location: "Andhra Pradesh",
    country: "India",
    image: meghalaya,
    gallery: [meghalaya, ladakh, spiti],
    durationDays: 3,
    durationNights: 2,
    price: 6999,
    rating: 4.5,
    reviews: 234,
    groupSize: "15–25",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Hyderabad", "Visakhapatnam"],
    pickup: "Araku Valley",
    drop: "Araku Valley",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb"],
    tagline: "Misty hills & tribal culture",
    description: "Experience the scenic beauty of Araku with its coffee plantations and tribal heritage.",
    highlights: ["Hill views", "Coffee estates", "Tribal village tours", "Waterfall visits"],
    inclusions: ["2 nights stay", "Meals", "Local tours", "Transfers"],
    exclusions: ["Personal expenses"],
    itinerary: [
      { day: 1, title: "Araku arrival", details: "Settlement & orientation." },
      { day: 2, title: "Hill exploration", details: "Coffee tours & village visit." },
      { day: 3, title: "Departure", details: "Waterfall visit & drop." },
    ],
    departures: [
      { date: "14 May 2026", spotsLeft: 10 },
      { date: "28 May 2026", spotsLeft: 14 },
    ],
  },
  {
    slug: "pondicherry",
    title: "Pondicherry Beach Getaway",
    location: "Tamil Nadu",
    country: "India",
    image: goa,
    gallery: [goa, bali, thailand],
    durationDays: 3,
    durationNights: 2,
    price: 7499,
    rating: 4.6,
    reviews: 567,
    groupSize: "15–25",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Chennai", "Bangalore"],
    pickup: "Pondicherry Beach",
    drop: "Pondicherry Beach",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "French colonial charm & beaches",
    description: "Relax in the charming coastal town with colonial architecture and peaceful beaches.",
    highlights: ["Beach walks", "Colonial architecture", "Auroville", "Local cafes"],
    inclusions: ["2 nights stay", "Breakfast", "Local tours", "Transfers"],
    exclusions: ["Meals", "Activities"],
    itinerary: [
      { day: 1, title: "Pondicherry arrival", details: "Beach exploration & colonial tour." },
      { day: 2, title: "Auroville & surroundings", details: "Spiritual visit & nature walks." },
      { day: 3, title: "Departure", details: "Last-minute shopping & drop." },
    ],
    departures: [
      { date: "09 May 2026", spotsLeft: 12 },
      { date: "23 May 2026", spotsLeft: 16 },
    ],
  },
  {
    slug: "arunachalam-pondicherry",
    title: "Arunachalam & Pondicherry Spiritual Tour",
    location: "Tamil Nadu",
    country: "India",
    image: kashmir,
    gallery: [kashmir, meghalaya, manali],
    durationDays: 4,
    durationNights: 3,
    price: 7499,
    rating: 4.8,
    reviews: 312,
    groupSize: "10–18",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Chennai", "Bangalore"],
    pickup: "Tiruvannamalai",
    drop: "Tiruvannamalai",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb"],
    tagline: "Sacred temple & coastal charm",
    description: "Spiritual journey combining the sacred Arunachaleswara temple with Pondicherry's serenity.",
    highlights: ["Temple circumambulation", "Spiritual sessions", "Beach time", "Local ashrams"],
    inclusions: ["3 nights stay", "Meals", "Temple tours", "Transfers"],
    exclusions: ["Personal items", "Tips"],
    itinerary: [
      { day: 1, title: "Tiruvannamalai arrival", details: "Temple visit & evening prayers." },
      { day: 2, title: "Sacred walks", details: "Circumambulation & meditation." },
      { day: 3, title: "Pondicherry day trip", details: "Coastal exploration." },
      { day: 4, title: "Departure", details: "Final prayers & drop." },
    ],
    departures: [
      { date: "11 Jun 2026", spotsLeft: 6 },
      { date: "25 Jun 2026", spotsLeft: 10 },
    ],
  },
  {
    slug: "lonavala",
    title: "Lonavala Hill Station Escape",
    location: "Maharashtra",
    country: "India",
    image: manali,
    gallery: [manali, meghalaya, ladakh],
    durationDays: 3,
    durationNights: 2,
    price: 7499,
    rating: 4.5,
    reviews: 678,
    groupSize: "15–25",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Mumbai", "Pune"],
    pickup: "Lonavala",
    drop: "Lonavala",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Monsoon magic & scenic viewpoints",
    description: "Quick getaway from Mumbai with scenic trekking, ancient forts, and valley views.",
    highlights: ["Duke's Nose trek", "Monsoon views", "Local caves", "Waterfall visit"],
    inclusions: ["2 nights stay", "Breakfast & dinner", "Guided trek", "Transfers"],
    exclusions: ["Personal activities"],
    itinerary: [
      { day: 1, title: "Lonavala arrival", details: "Check-in & local exploration." },
      { day: 2, title: "Duke's Nose trek", details: "Scenic valley views & lunch picnic." },
      { day: 3, title: "Departure", details: "Cave visit & departure." },
    ],
    departures: [
      { date: "13 May 2026", spotsLeft: 9 },
      { date: "27 May 2026", spotsLeft: 13 },
    ],
  },
  {
    slug: "rajmachi-visapur",
    title: "Rajmachi & Visapur Fort Trek",
    location: "Maharashtra",
    country: "India",
    image: spiti,
    gallery: [spiti, ladakh, kashmir],
    durationDays: 2,
    durationNights: 1,
    price: 6499,
    rating: 4.7,
    reviews: 423,
    groupSize: "12–20",
    difficulty: "Moderate",
    category: "weekend",
    departureCities: ["Mumbai", "Pune"],
    pickup: "Rajmachi Village",
    drop: "Rajmachi Village",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Twin forts & misty mornings",
    description: "Trek to the scenic Rajmachi and Visapur forts with stunning views and night camping.",
    highlights: ["Fort exploration", "Sunrise trek", "Scenic camping", "Local guides"],
    inclusions: ["1 night camp", "Meals", "Trek guide", "Transfers"],
    exclusions: ["Equipment rental"],
    itinerary: [
      { day: 1, title: "Trek to Rajmachi", details: "Fort exploration & camping setup." },
      { day: 2, title: "Visapur & descent", details: "Morning trek & descent." },
    ],
    departures: [
      { date: "16 May 2026", spotsLeft: 8 },
      { date: "30 May 2026", spotsLeft: 12 },
    ],
  },
  {
    slug: "gokarna-hampi",
    title: "Gokarna & Hampi Cultural Trail",
    location: "Karnataka",
    country: "India",
    image: bali,
    gallery: [bali, goa, meghalaya],
    durationDays: 4,
    durationNights: 3,
    price: 6499,
    rating: 4.8,
    reviews: 345,
    groupSize: "12–18",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Bangalore", "Goa"],
    pickup: "Gokarna",
    drop: "Hampi",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb"],
    tagline: "Beach vibes & ancient ruins",
    description: "Combine serene Gokarna beaches with the mystical temples and ruins of Hampi.",
    highlights: ["Gokarna beaches", "Hampi temples", "Ruin exploration", "River activities"],
    inclusions: ["3 nights stay", "Breakfast & dinner", "Local tours", "Transfers"],
    exclusions: ["Lunch", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Gokarna arrival", details: "Beach settlement & exploration." },
      { day: 2, title: "Gokarna day trip", details: "Beach hopping & water activities." },
      { day: 3, title: "Drive to Hampi", details: "Temple exploration." },
      { day: 4, title: "Hampi ruins", details: "Detailed sightseeing & departure." },
    ],
    departures: [
      { date: "07 May 2026", spotsLeft: 7 },
      { date: "21 May 2026", spotsLeft: 11 },
    ],
  },
  {
    slug: "gokarna-udupi",
    title: "Gokarna & Udupi Beach Combo",
    location: "Karnataka",
    country: "India",
    image: goa,
    gallery: [goa, bali, thailand],
    durationDays: 3,
    durationNights: 2,
    price: 5499,
    rating: 4.6,
    reviews: 289,
    groupSize: "15–25",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Bangalore", "Goa", "Mangalore"],
    pickup: "Gokarna",
    drop: "Udupi",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Two coastal gems in one trip",
    description: "Experience the best of Karnataka's coast with Gokarna's laid-back vibe and Udupi's temples.",
    highlights: ["Beach stays", "Temple visits", "Water sports", "Local cuisine"],
    inclusions: ["2 nights stay", "Meals", "Local tours", "Transfers"],
    exclusions: ["Personal activities"],
    itinerary: [
      { day: 1, title: "Gokarna", details: "Beach arrival & evening exploration." },
      { day: 2, title: "Udupi travel", details: "Temple visit & beach time." },
      { day: 3, title: "Departure", details: "Last beach time & drop." },
    ],
    departures: [
      { date: "18 May 2026", spotsLeft: 10 },
      { date: "01 Jun 2026", spotsLeft: 14 },
    ],
  },
  {
    slug: "andharban-devkund",
    title: "Andharban & Devkund Waterfall Trek",
    location: "Maharashtra",
    country: "India",
    image: manali,
    gallery: [manali, meghalaya, spiti],
    durationDays: 2,
    durationNights: 1,
    price: 6499,
    rating: 4.7,
    reviews: 512,
    groupSize: "10–18",
    difficulty: "Moderate",
    category: "weekend",
    departureCities: ["Mumbai", "Pune"],
    pickup: "Andharban Trailhead",
    drop: "Andharban Trailhead",
    months: ["Jun", "Jul", "Aug", "Sep", "Oct"],
    tagline: "Dark forest & pristine waterfall",
    description: "Trek through the enchanting dark forest to reach the spectacular Devkund waterfall.",
    highlights: ["Forest trek", "Devkund waterfall", "Pool swimming", "Monsoon beauty"],
    inclusions: ["1 night camp", "Meals", "Trek guide", "Transfers"],
    exclusions: ["Equipment", "Personal items"],
    itinerary: [
      { day: 1, title: "Trek to Devkund", details: "Dark forest & waterfall camp." },
      { day: 2, title: "Pool time & descent", details: "Swimming & trek back." },
    ],
    departures: [
      { date: "20 Jun 2026", spotsLeft: 6 },
      { date: "04 Jul 2026", spotsLeft: 9 },
    ],
  },
  {
    slug: "ananthagiri_hills_camping",
    title: "Anathagiri Camping Escape",
    location: "Telangana",
    country: "India",
    image: meghalaya,
    gallery: [meghalaya, spiti, ladakh],
    durationDays: 2,
    durationNights: 1,
    price: 3299,
    rating: 4.6,
    reviews: 287,
    groupSize: "12–20",
    difficulty: "Easy",
    category: "weekend",
    departureCities: ["Hyderabad"],
    pickup: "Anathagiri",
    drop: "Anathagiri",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Hill camping & temple vibes",
    description: "A short fun weekend escape with camping, nature trails, and spiritual temple visits in the Telangana hills.",
    highlights: ["Hill camping", "Nature trails", "Temple visit", "Scenic viewpoints", "Campfire & local food"],
    inclusions: ["1 night camp", "Meals", "Trek guide", "Transfers"],
    exclusions: ["Equipment rental", "Personal items"],
    itinerary: [
      { day: 1, title: "Arrive & camp setup", details: "Anathagiri temple visit & camping preparation." },
      { day: 2, title: "Nature trail & descent", details: "Morning trail walk & departure." },
    ],
    departures: [
      { date: "17 May 2026", spotsLeft: 14 },
      { date: "31 May 2026", spotsLeft: 16 },
    ],
  },

  // BACKPACKING TRIPS (9)
  {
    slug: "kerala",
    title: "Kerala Backpacking Adventure",
    location: "Kerala",
    country: "India",
    image: meghalaya,
    gallery: [meghalaya, kashmir, bali],
    durationDays: 7,
    durationNights: 6,
    price: 11999,
    rating: 4.8,
    reviews: 756,
    groupSize: "10–20",
    difficulty: "Easy",
    category: "backpacking",
    departureCities: ["Kochi", "Thiruvananthapuram"],
    pickup: "Kochi Airport",
    drop: "Kochi Airport",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Backwaters, beaches & spice markets",
    description: "An immersive Kerala experience with backwater cruises, beach stays, and spice plantation tours.",
    highlights: ["Backwater cruise", "Alleppey houseboat", "Cochin heritage walk", "Spice market tour"],
    inclusions: ["6 nights stay", "Daily breakfast", "Houseboat cruise", "Local transfers"],
    exclusions: ["Flights", "Lunch & dinner"],
    itinerary: [
      { day: 1, title: "Kochi arrival", details: "Fort Kochi heritage walk." },
      { day: 2, title: "Backwater cruise", details: "Houseboat experience." },
      { day: 3, title: "Alleppey beaches", details: "Relaxation & swimming." },
      { day: 4, title: "Spice plantation", details: "Tour & lunch." },
      { day: 5, title: "Kumbalangi village", details: "Fishing village experience." },
      { day: 6, title: "Kochi to Thiruvananthapuram", details: "Beach time." },
      { day: 7, title: "Departure", details: "Airport drop." },
    ],
    departures: [
      { date: "12 Oct 2026", spotsLeft: 8 },
      { date: "26 Oct 2026", spotsLeft: 12 },
    ],
  },
  {
    slug: "shimla-manali",
    title: "Shimla & Manali Backpacking",
    location: "Himachal Pradesh",
    country: "India",
    image: manali,
    gallery: [manali, spiti, ladakh],
    durationDays: 8,
    durationNights: 7,
    price: 11999,
    rating: 4.7,
    reviews: 634,
    groupSize: "12–20",
    difficulty: "Moderate",
    category: "backpacking",
    departureCities: ["Delhi", "Chandigarh"],
    pickup: "Shimla",
    drop: "Manali",
    months: ["Mar", "Apr", "May", "Jun", "Sep", "Oct"],
    tagline: "Mountains, cafes & adventure trails",
    description: "A classic backpacking route through Himalayan hill stations with budget stays and local experiences.",
    highlights: ["Mall road wandering", "Old Manali vibe", "Solang valley", "Parvati river trek"],
    inclusions: ["7 nights budget stay", "Daily breakfast", "Local guide", "Transfers"],
    exclusions: ["Meals beyond breakfast", "Activities"],
    itinerary: [
      { day: 1, title: "Shimla arrival", details: "Mall road exploration." },
      { day: 2, title: "Shimla local", details: "Jakhoo temple & nature walks." },
      { day: 3, title: "Shimla to Manali", details: "Scenic drive." },
      { day: 4, title: "Old Manali", details: "Cafe hopping & river time." },
      { day: 5, title: "Solang valley", details: "Adventure activities." },
      { day: 6, title: "Kasol trek", details: "Riverside trek." },
      { day: 7, title: "Manikaran", details: "Hot springs & relaxation." },
      { day: 8, title: "Departure", details: "Last-minute shopping." },
    ],
    departures: [
      { date: "05 Apr 2026", spotsLeft: 10 },
      { date: "19 Apr 2026", spotsLeft: 14 },
    ],
  },
  {
    slug: "ooty-kodaikanal",
    title: "Ooty & Kodaikanal Backpacking",
    location: "Tamil Nadu",
    country: "India",
    image: ladakh,
    gallery: [ladakh, meghalaya, manali],
    durationDays: 6,
    durationNights: 5,
    price: 11999,
    rating: 4.6,
    reviews: 523,
    groupSize: "12–20",
    difficulty: "Easy",
    category: "backpacking",
    departureCities: ["Bangalore", "Coimbatore"],
    pickup: "Ooty",
    drop: "Kodaikanal",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb"],
    tagline: "South Indian hill stations on a budget",
    description: "Explore the Nilgiri hills with Toy Train rides, botanical gardens, and lake adventures.",
    highlights: ["Toy train ride", "Botanical gardens", "Lake boating", "Trekking trails"],
    inclusions: ["5 nights budget stay", "Breakfast", "Local guide", "Transfers"],
    exclusions: ["Lunch & dinner"],
    itinerary: [
      { day: 1, title: "Ooty arrival", details: "Orientation & local walk." },
      { day: 2, title: "Ooty sightseeing", details: "Botanical gardens & toy train." },
      { day: 3, title: "Ooty to Kodaikanal", details: "Scenic drive." },
      { day: 4, title: "Kodaikanal lakes", details: "Boating & trekking." },
      { day: 5, title: "Sunrise trek", details: "Hill exploration." },
      { day: 6, title: "Departure", details: "Last-minute views." },
    ],
    departures: [
      { date: "15 Oct 2026", spotsLeft: 9 },
      { date: "29 Oct 2026", spotsLeft: 13 },
    ],
  },
  {
    slug: "rajasthan",
    title: "Rajasthan Desert Backpacking",
    location: "Rajasthan",
    country: "India",
    image: kashmir,
    gallery: [kashmir, spiti, meghalaya],
    durationDays: 10,
    durationNights: 9,
    price: 17999,
    rating: 4.9,
    reviews: 892,
    groupSize: "10–18",
    difficulty: "Moderate",
    category: "backpacking",
    departureCities: ["Delhi", "Jaipur"],
    pickup: "Jaipur",
    drop: "Jodhpur",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Palaces, deserts & vibrant culture",
    description: "An iconic Rajasthan tour covering Jaipur, Pushkar, Jodhpur with desert camps and camel safaris.",
    highlights: ["City Palace", "Hawa Mahal", "Desert safari", "Camel ride", "Pushkar fair"],
    inclusions: ["9 nights stay", "Breakfast", "Desert camp", "Local guide", "Camel safari"],
    exclusions: ["Lunch & dinner", "Activities"],
    itinerary: [
      { day: 1, title: "Jaipur arrival", details: "Pink City exploration." },
      { day: 2, title: "Amber Fort", details: "Fort tour & elephant ride." },
      { day: 3, title: "Jaipur to Pushkar", details: "Sacred town visit." },
      { day: 4, title: "Pushkar market", details: "Local bazaar & temple." },
      { day: 5, title: "Desert trek", details: "Camel safari & sunset." },
      { day: 6, title: "Jodhpur drive", details: "Scenic route." },
      { day: 7, title: "Mehrangarh Fort", details: "Fort exploration." },
      { day: 8, title: "Jodhpur local", details: "Blue city wandering." },
      { day: 9, title: "Osian desert", details: "Sand dunes & camping." },
      { day: 10, title: "Departure", details: "Final sights & drop." },
    ],
    departures: [
      { date: "01 Nov 2026", spotsLeft: 7 },
      { date: "15 Nov 2026", spotsLeft: 11 },
    ],
  },
  {
    slug: "meghalaya",
    title: "Meghalaya Backpacking Adventure",
    location: "Meghalaya",
    country: "India",
    image: meghalaya,
    gallery: [meghalaya, kashmir, ladakh],
    durationDays: 7,
    durationNights: 6,
    price: 17999,
    rating: 4.8,
    reviews: 567,
    groupSize: "10–18",
    difficulty: "Moderate",
    category: "backpacking",
    departureCities: ["Guwahati", "Shillong"],
    pickup: "Guwahati Airport",
    drop: "Guwahati Airport",
    months: ["Jun", "Jul", "Aug", "Sep", "Oct"],
    tagline: "Living root bridges & misty valleys",
    description: "Trek through Meghalaya's enchanting landscapes with living root bridges and tribal villages.",
    highlights: ["Double Decker bridge trek", "Living root bridge", "Mawlynnong village", "Krang Suri falls"],
    inclusions: ["6 nights stay", "Meals", "Trek guide", "Local tours", "Transfers"],
    exclusions: ["Personal items"],
    itinerary: [
      { day: 1, title: "Guwahati to Shillong", details: "City orientation." },
      { day: 2, title: "Shillong to Cherrapunji", details: "Mawkdok valley." },
      { day: 3, title: "Double Decker trek", details: "Nongriat village stay." },
      { day: 4, title: "Living root bridge", details: "Trek adventure." },
      { day: 5, title: "Mawlynnong", details: "Cleanest village tour." },
      { day: 6, title: "Krang Suri falls", details: "Waterfall swimming." },
      { day: 7, title: "Return", details: "Final exploration & drop." },
    ],
    departures: [
      { date: "12 Jul 2026", spotsLeft: 8 },
      { date: "26 Jul 2026", spotsLeft: 12 },
    ],
  },
  {
    slug: "kashmir",
    title: "Kashmir Backpacking Circuit",
    location: "Kashmir",
    country: "India",
    image: kashmir,
    gallery: [kashmir, ladakh, spiti],
    durationDays: 10,
    durationNights: 9,
    price: 11999,
    rating: 4.9,
    reviews: 445,
    groupSize: "10–16",
    difficulty: "Challenging",
    category: "backpacking",
    departureCities: ["Srinagar", "Delhi"],
    pickup: "Srinagar Airport",
    drop: "Srinagar Airport",
    months: ["Jul", "Aug", "Sep"],
    tagline: "Paradise valley & alpine lakes",
    description: "A comprehensive Kashmir adventure with treks, houseboats, and mountain circuits.",
    highlights: ["Great Lakes trek", "Houseboat stay", "Pahalgam valley", "Gulmarg meadows"],
    inclusions: ["9 nights stay", "Daily breakfast", "Trek guide", "Houseboat", "Transfers"],
    exclusions: ["Lunch & dinner"],
    itinerary: [
      { day: 1, title: "Srinagar arrival", details: "Houseboat check-in." },
      { day: 2, title: "Dal Lake cruise", details: "Floating gardens & shrines." },
      { day: 3, title: "Trek prep", details: "Gear collection & briefing." },
      { day: 4, title: "Great Lakes Day 1", details: "Vishansar lake camp." },
      { day: 5, title: "Great Lakes Day 2", details: "Krishnasar lake." },
      { day: 6, title: "Gadsar pass", details: "High altitude camp." },
      { day: 7, title: "Satsar lake", details: "Twin lakes camp." },
      { day: 8, title: "Pahalgam", details: "Trek descent & relax." },
      { day: 9, title: "Gulmarg", details: "Meadow exploration." },
      { day: 10, title: "Departure", details: "Final shopping & drop." },
    ],
    departures: [
      { date: "15 Jul 2026", spotsLeft: 5 },
      { date: "29 Jul 2026", spotsLeft: 9 },
    ],
  },
  {
    slug: "goa",
    title: "Goa Backpacking Paradise",
    location: "Goa",
    country: "India",
    image: goa,
    gallery: [goa, bali, thailand],
    durationDays: 7,
    durationNights: 6,
    price: 11999,
    rating: 4.7,
    reviews: 1234,
    groupSize: "15–30",
    difficulty: "Easy",
    category: "backpacking",
    departureCities: ["Mumbai", "Bangalore", "Delhi"],
    pickup: "North Goa",
    drop: "North Goa",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Beaches, shacks & party vibes",
    description: "The ultimate Goa experience with beach parties, water sports, and budget stay options.",
    highlights: ["Beach hopping", "Water sports", "Sunset parties", "Local markets", "Fort visits"],
    inclusions: ["6 nights budget hostel", "Daily breakfast", "Local tours", "Transfers"],
    exclusions: ["Meals beyond breakfast", "Activities"],
    itinerary: [
      { day: 1, title: "Goa arrival", details: "Beach orientation & settle." },
      { day: 2, title: "Anjuna beach", details: "Flea market & beach clubs." },
      { day: 3, title: "Water sports", details: "Parasailing & jet ski." },
      { day: 4, title: "Old Goa tour", details: "Portuguese heritage & churches." },
      { day: 5, title: "Spice plantation", details: "Tour & lunch." },
      { day: 6, title: "Sunset party", details: "Sunset cruise & beach party." },
      { day: 7, title: "Free day", details: "Last-minute activities." },
    ],
    departures: [
      { date: "08 Oct 2026", spotsLeft: 15 },
      { date: "22 Oct 2026", spotsLeft: 20 },
    ],
  },
  {
    slug: "sikkim-gangtok",
    title: "Sikkim & Gangtok Backpacking",
    location: "Sikkim",
    country: "India",
    image: ladakh,
    gallery: [ladakh, meghalaya, kashmir],
    durationDays: 8,
    durationNights: 7,
    price: 17999,
    rating: 4.8,
    reviews: 389,
    groupSize: "10–18",
    difficulty: "Moderate",
    category: "backpacking",
    departureCities: ["Siliguri", "Guwahati"],
    pickup: "Gangtok",
    drop: "Gangtok",
    months: ["Apr", "May", "Sep", "Oct"],
    tagline: "Buddhist monasteries & Kanchenjunga views",
    description: "Explore Sikkim's spiritual culture, monasteries, and mountain peaks with budget-friendly stays.",
    highlights: ["Rumtek monastery", "Tsomgo lake", "Nathula pass", "Kanchenjunga view", "Buddhist culture"],
    inclusions: ["7 nights stay", "Breakfast", "Local guide", "Inner line permit", "Transfers"],
    exclusions: ["Lunch & dinner"],
    itinerary: [
      { day: 1, title: "Gangtok arrival", details: "City orientation." },
      { day: 2, title: "Rumtek monastery", details: "Buddhist visit." },
      { day: 3, title: "Nathula pass", details: "Border exploration." },
      { day: 4, title: "Tsomgo lake", details: "High altitude lake." },
      { day: 5, title: "Gangtok local", details: "Market & temples." },
      { day: 6, title: "Pemayangste monastery", details: "Day trip." },
      { day: 7, title: "Kanchenjunga trek", details: "Base camp hike." },
      { day: 8, title: "Departure", details: "Final sightseeing." },
    ],
    departures: [
      { date: "20 Apr 2026", spotsLeft: 8 },
      { date: "04 May 2026", spotsLeft: 12 },
    ],
  },
  {
    slug: "goa-gokarna-dandeli",
    title: "Goa, Gokarna & Dandeli Adventure",
    location: "Goa & Karnataka",
    country: "India",
    image: goa,
    gallery: [goa, bali, meghalaya],
    durationDays: 8,
    durationNights: 7,
    price: 11999,
    rating: 4.8,
    reviews: 456,
    groupSize: "12–20",
    difficulty: "Easy",
    category: "backpacking",
    departureCities: ["Bangalore", "Goa", "Mumbai"],
    pickup: "North Goa",
    drop: "Dandeli",
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    tagline: "Beaches, backwaters & river adventures",
    description: "A complete coastal backpacking journey combining Goa's party scene with Gokarna's tranquility and Dandeli's adventure.",
    highlights: ["Beach parties", "Water rafting", "River camping", "Sunset cruises", "Water sports"],
    inclusions: ["7 nights budget stay", "Breakfast & dinner", "Rafting activity", "Local guide", "Transfers"],
    exclusions: ["Personal items", "Tips"],
    itinerary: [
      { day: 1, title: "North Goa", details: "Beach settlement." },
      { day: 2, title: "Goa parties", details: "Beach clubs & sunset." },
      { day: 3, title: "Goa to Gokarna", details: "Scenic drive." },
      { day: 4, title: "Gokarna beaches", details: "Beach hopping." },
      { day: 5, title: "Gokarna to Dandeli", details: "River arrival." },
      { day: 6, title: "Dandeli rafting", details: "White water rafting." },
      { day: 7, title: "River camping", details: "Night under stars." },
      { day: 8, title: "Departure", details: "Final exploration." },
    ],
    departures: [
      { date: "10 Oct 2026", spotsLeft: 10 },
      { date: "24 Oct 2026", spotsLeft: 14 },
    ],
  },
];

export const getTrip = (slug: string) => trips.find((t) => t.slug === slug);

export const testimonials = [
  {
    name: "Ananya Sharma",
    trip: "Gokarna & Dandeli Weekend",
    rating: 5,
    text: "Honestly the best trip I've ever taken. The team made every moment special and the rafting experience was unforgettable.",
    avatar: "AS",
  },
  {
    name: "Rohan Mehta",
    trip: "Kashmir Backpacking Circuit",
    rating: 5,
    text: "Tough adventure but the team made it feel safe. Stays, food, gear — everything was top class. Already booked another trip!",
    avatar: "RM",
  },
  {
    name: "Priya Iyer",
    trip: "Kerala Backpacking Adventure",
    rating: 5,
    text: "Solo female traveller — felt totally safe and made lifelong friends. Globo Traveller knows what they're doing.",
    avatar: "PI",
  },
  {
    name: "Karan Patel",
    trip: "Shimla & Manali Backpacking",
    rating: 4.5,
    text: "Quick mountain escape that was genuinely fun. Old Manali vibes were perfect. Will be back for more!",
    avatar: "KP",
  },
];

export const faqs = [
  {
    q: "How are Globo Traveller's group sizes managed?",
    a: "We keep groups intentionally small — 10 to 25 travellers per departure — with a dedicated trip captain so you're never just a number on a bus.",
  },
  {
    q: "Are your trips suitable for solo travellers?",
    a: "Absolutely. 60% of our travellers are solo. We do same-gender room-sharing by default, and our captains make sure everyone is included.",
  },
  {
    q: "What's your cancellation & refund policy?",
    a: "Free cancellation up to 21 days before departure. 50% refund 7–20 days before. Beyond that, we offer a credit voucher valid for 12 months.",
  },
  {
    q: "How do I pay? Do you support EMI?",
    a: "We accept UPI, all major cards, net banking, and EMI on cards above ₹5,000. Pay 25% to confirm, rest before departure.",
  },
  {
    q: "What if my trip is cancelled due to weather?",
    a: "If we cancel for safety reasons, you get a full refund or a free reschedule — your choice, no questions asked.",
  },
];
