/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips/index'
import { Route as FaqIndexRouteImport } from './routes/faq/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as TripsTreasuresOfKarnatakaRouteImport } from './routes/trips/treasures-of-karnataka'
import { Route as TripsSlugRouteImport } from './routes/trips/$slug'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalCancellationRouteImport } from './routes/legal/cancellation'
import { Route as BookingConfirmationRouteImport } from './routes/booking/confirmation'
import { Route as BookingSlugRouteImport } from './routes/booking/$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TripsRoute,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTreasuresOfKarnatakaRoute =
  TripsTreasuresOfKarnatakaRouteImport.update({
    id: '/trips/treasures-of-karnataka',
    path: '/trips/treasures-of-karnataka',
    getParentRoute: () => rootRouteImport,
  } as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCancellationRoute = LegalCancellationRouteImport.update({
  id: '/legal/cancellation',
  path: '/legal/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking/confirmation',
  path: '/booking/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSlugRoute = BookingSlugRouteImport.update({
  id: '/booking/$slug',
  path: '/booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/legal/cancellation': typeof LegalCancellationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/treasures-of-karnataka': typeof TripsTreasuresOfKarnatakaRoute
  '/blogs/': typeof BlogsIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/legal/cancellation': typeof LegalCancellationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/treasures-of-karnataka': typeof TripsTreasuresOfKarnatakaRoute
  '/blogs': typeof BlogsIndexRoute
  '/contact': typeof ContactIndexRoute
  '/faq': typeof FaqIndexRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/legal/cancellation': typeof LegalCancellationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/treasures-of-karnataka': typeof TripsTreasuresOfKarnatakaRoute
  '/blogs/': typeof BlogsIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs/$slug'
    | '/booking/$slug'
    | '/booking/confirmation'
    | '/legal/cancellation'
    | '/legal/privacy'
    | '/legal/terms'
    | '/trips/$slug'
    | '/trips/treasures-of-karnataka'
    | '/blogs/'
    | '/contact/'
    | '/faq/'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs/$slug'
    | '/booking/$slug'
    | '/booking/confirmation'
    | '/legal/cancellation'
    | '/legal/privacy'
    | '/legal/terms'
    | '/trips/$slug'
    | '/trips/treasures-of-karnataka'
    | '/blogs'
    | '/contact'
    | '/faq'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs/$slug'
    | '/booking/$slug'
    | '/booking/confirmation'
    | '/legal/cancellation'
    | '/legal/privacy'
    | '/legal/terms'
    | '/trips/$slug'
    | '/trips/treasures-of-karnataka'
    | '/blogs/'
    | '/contact/'
    | '/faq/'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  BookingSlugRoute: typeof BookingSlugRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  LegalCancellationRoute: typeof LegalCancellationRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  TripsSlugRoute: typeof TripsSlugRoute
  TripsTreasuresOfKarnatakaRoute: typeof TripsTreasuresOfKarnatakaRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  FaqIndexRoute: typeof FaqIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof TripsRoute
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/treasures-of-karnataka': {
      id: '/trips/treasures-of-karnataka'
      path: '/trips/treasures-of-karnataka'
      fullPath: '/trips/treasures-of-karnataka'
      preLoaderRoute: typeof TripsTreasuresOfKarnatakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cancellation': {
      id: '/legal/cancellation'
      path: '/legal/cancellation'
      fullPath: '/legal/cancellation'
      preLoaderRoute: typeof LegalCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation': {
      id: '/booking/confirmation'
      path: '/booking/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$slug': {
      id: '/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/booking/$slug'
      preLoaderRoute: typeof BookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  BookingSlugRoute: BookingSlugRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  LegalCancellationRoute: LegalCancellationRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  TripsSlugRoute: TripsSlugRoute,
  TripsTreasuresOfKarnatakaRoute: TripsTreasuresOfKarnatakaRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  FaqIndexRoute: FaqIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
