/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsTreasuresOfKarnatakaRouteImport } from './routes/trips.treasures-of-karnataka'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCancellationRouteImport } from './routes/legal.cancellation'
import { Route as BookingConfirmationRouteImport } from './routes/booking.confirmation'
import { Route as BookingSlugRouteImport } from './routes/booking.$slug'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTreasuresOfKarnatakaRoute =
  TripsTreasuresOfKarnatakaRouteImport.update({
    id: '/treasures-of-karnataka',
    path: '/treasures-of-karnataka',
    getParentRoute: () => TripsRoute,
  } as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TripsRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCancellationRoute = LegalCancellationRouteImport.update({
  id: '/legal/cancellation',
  path: '/legal/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking/confirmation',
  path: '/booking/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSlugRoute = BookingSlugRouteImport.update({
  id: '/booking/$slug',
  path: '/booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/trips': typeof TripsRouteWithChildren
  '/booking/$slug': typeof BookingSlugRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/legal/cancellation': typeof LegalCancellationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/treasures-of-karnataka': typeof TripsTreasuresOfKarnatakaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/trips': typeof TripsRouteWithChildren
  '/booking/$slug': typeof BookingSlugRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/legal/cancellation': typeof LegalCancellationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/treasures-of-karnataka': typeof TripsTreasuresOfKarnatakaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/trips': typeof TripsRouteWithChildren
  '/booking/$slug': typeof BookingSlugRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/legal/cancellation': typeof LegalCancellationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/treasures-of-karnataka': typeof TripsTreasuresOfKarnatakaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/trips'
    | '/booking/$slug'
    | '/booking/confirmation'
    | '/legal/cancellation'
    | '/legal/privacy'
    | '/legal/terms'
    | '/trips/$slug'
    | '/trips/treasures-of-karnataka'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/trips'
    | '/booking/$slug'
    | '/booking/confirmation'
    | '/legal/cancellation'
    | '/legal/privacy'
    | '/legal/terms'
    | '/trips/$slug'
    | '/trips/treasures-of-karnataka'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/trips'
    | '/booking/$slug'
    | '/booking/confirmation'
    | '/legal/cancellation'
    | '/legal/privacy'
    | '/legal/terms'
    | '/trips/$slug'
    | '/trips/treasures-of-karnataka'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  TripsRoute: typeof TripsRouteWithChildren
  BookingSlugRoute: typeof BookingSlugRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  LegalCancellationRoute: typeof LegalCancellationRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/treasures-of-karnataka': {
      id: '/trips/treasures-of-karnataka'
      path: '/treasures-of-karnataka'
      fullPath: '/trips/treasures-of-karnataka'
      preLoaderRoute: typeof TripsTreasuresOfKarnatakaRouteImport
      parentRoute: typeof TripsRoute
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof TripsRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cancellation': {
      id: '/legal/cancellation'
      path: '/legal/cancellation'
      fullPath: '/legal/cancellation'
      preLoaderRoute: typeof LegalCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation': {
      id: '/booking/confirmation'
      path: '/booking/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$slug': {
      id: '/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/booking/$slug'
      preLoaderRoute: typeof BookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TripsRouteChildren {
  TripsSlugRoute: typeof TripsSlugRoute
  TripsTreasuresOfKarnatakaRoute: typeof TripsTreasuresOfKarnatakaRoute
}

const TripsRouteChildren: TripsRouteChildren = {
  TripsSlugRoute: TripsSlugRoute,
  TripsTreasuresOfKarnatakaRoute: TripsTreasuresOfKarnatakaRoute,
}

const TripsRouteWithChildren = TripsRoute._addFileChildren(TripsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  TripsRoute: TripsRouteWithChildren,
  BookingSlugRoute: BookingSlugRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  LegalCancellationRoute: LegalCancellationRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
