/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips/index'
import { Route as FaqIndexRouteImport } from './routes/faq/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as TripsWayanadRouteImport } from './routes/trips/wayanad'
import { Route as TripsTreasuresOfKarnatakaRouteImport } from './routes/trips/treasures-of-karnataka'
import { Route as TripsOoty_and_coonoorRouteImport } from './routes/trips/ooty_and_coonoor'
import { Route as TripsKallu_falls_harishchandragadRouteImport } from './routes/trips/kallu_falls_harishchandragad'
import { Route as TripsIsha_ootyRouteImport } from './routes/trips/isha_ooty'
import { Route as TripsGokarna_dandeliRouteImport } from './routes/trips/gokarna_dandeli'
import { Route as TripsArakuRouteImport } from './routes/trips/araku'
import { Route as TripsArunachalam_PondicherryRouteImport } from './routes/trips/Arunachalam_Pondicherry'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalCancellationRouteImport } from './routes/legal/cancellation'
import { Route as BookingConfirmationRouteImport } from './routes/booking/confirmation'
import { Route as BookingSlugRouteImport } from './routes/booking/$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsWayanadRoute = TripsWayanadRouteImport.update({
  id: '/trips/wayanad',
  path: '/trips/wayanad',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTreasuresOfKarnatakaRoute =
  TripsTreasuresOfKarnatakaRouteImport.update({
    id: '/trips/treasures-of-karnataka',
    path: '/trips/treasures-of-karnataka',
    getParentRoute: () => rootRouteImport,
  } as any)
const TripsOoty_and_coonoorRoute = TripsOoty_and_coonoorRouteImport.update({
  id: '/trips/ooty_and_coonoor',
  path: '/trips/ooty_and_coonoor',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsKallu_falls_harishchandragadRoute =
  TripsKallu_falls_harishchandragadRouteImport.update({
    id: '/trips/kallu_falls_harishchandragad',
    path: '/trips/kallu_falls_harishchandragad',
    getParentRoute: () => rootRouteImport,
  } as any)
const TripsIsha_ootyRoute = TripsIsha_ootyRouteImport.update({
  id: '/trips/isha_ooty',
  path: '/trips/isha_ooty',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsGokarna_dandeliRoute = TripsGokarna_dandeliRouteImport.update({
  id: '/trips/gokarna_dandeli',
  path: '/trips/gokarna_dandeli',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsArakuRoute = TripsArakuRouteImport.update({
  id: '/trips/araku',
  path: '/trips/araku',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsArunachalam_PondicherryRoute =
  TripsArunachalam_PondicherryRouteImport.update({
    id: '/trips/Arunachalam_Pondicherry',
    path: '/trips/Arunachalam_Pondicherry',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCancellationRoute = LegalCancellationRouteImport.update({
  id: '/legal/cancellation',
  path: '/legal/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking/confirmation',
  path: '/booking/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSlugRoute = BookingSlugRouteImport.update({
  id: '/booking/$slug',
  path: '/booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/legal/cancellation': typeof LegalCancellationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trips/Arunachalam_Pondicherry': typeof TripsArunachalam_PondicherryRoute
  '/trips/araku': typeof TripsArakuRoute
  '/trips/gokarna_dandeli': typeof TripsGokarna_dandeliRoute
  '/trips/isha_ooty': typeof TripsIsha_ootyRoute
  '/trips/kallu_falls_harishchandragad': typeof TripsKallu_falls_harishchandragadRoute
  '/trips/ooty_and_coonoor': typeof TripsOoty_and_coonoorRoute
  '/trips/treasures-of-karnataka': typeof TripsTreasuresOfKarnatakaRoute
  '/trips/wayanad': typeof TripsWayanadRoute
  '/blogs/': typeof BlogsIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/legal/cancellation': typeof LegalCancellationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trips/Arunachalam_Pondicherry': typeof TripsArunachalam_PondicherryRoute
  '/trips/araku': typeof TripsArakuRoute
  '/trips/gokarna_dandeli': typeof TripsGokarna_dandeliRoute
  '/trips/isha_ooty': typeof TripsIsha_ootyRoute
  '/trips/kallu_falls_harishchandragad': typeof TripsKallu_falls_harishchandragadRoute
  '/trips/ooty_and_coonoor': typeof TripsOoty_and_coonoorRoute
  '/trips/treasures-of-karnataka': typeof TripsTreasuresOfKarnatakaRoute
  '/trips/wayanad': typeof TripsWayanadRoute
  '/blogs': typeof BlogsIndexRoute
  '/contact': typeof ContactIndexRoute
  '/faq': typeof FaqIndexRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/legal/cancellation': typeof LegalCancellationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trips/Arunachalam_Pondicherry': typeof TripsArunachalam_PondicherryRoute
  '/trips/araku': typeof TripsArakuRoute
  '/trips/gokarna_dandeli': typeof TripsGokarna_dandeliRoute
  '/trips/isha_ooty': typeof TripsIsha_ootyRoute
  '/trips/kallu_falls_harishchandragad': typeof TripsKallu_falls_harishchandragadRoute
  '/trips/ooty_and_coonoor': typeof TripsOoty_and_coonoorRoute
  '/trips/treasures-of-karnataka': typeof TripsTreasuresOfKarnatakaRoute
  '/trips/wayanad': typeof TripsWayanadRoute
  '/blogs/': typeof BlogsIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs/$slug'
    | '/booking/$slug'
    | '/booking/confirmation'
    | '/legal/cancellation'
    | '/legal/privacy'
    | '/legal/terms'
    | '/trips/Arunachalam_Pondicherry'
    | '/trips/araku'
    | '/trips/gokarna_dandeli'
    | '/trips/isha_ooty'
    | '/trips/kallu_falls_harishchandragad'
    | '/trips/ooty_and_coonoor'
    | '/trips/treasures-of-karnataka'
    | '/trips/wayanad'
    | '/blogs/'
    | '/contact/'
    | '/faq/'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs/$slug'
    | '/booking/$slug'
    | '/booking/confirmation'
    | '/legal/cancellation'
    | '/legal/privacy'
    | '/legal/terms'
    | '/trips/Arunachalam_Pondicherry'
    | '/trips/araku'
    | '/trips/gokarna_dandeli'
    | '/trips/isha_ooty'
    | '/trips/kallu_falls_harishchandragad'
    | '/trips/ooty_and_coonoor'
    | '/trips/treasures-of-karnataka'
    | '/trips/wayanad'
    | '/blogs'
    | '/contact'
    | '/faq'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs/$slug'
    | '/booking/$slug'
    | '/booking/confirmation'
    | '/legal/cancellation'
    | '/legal/privacy'
    | '/legal/terms'
    | '/trips/Arunachalam_Pondicherry'
    | '/trips/araku'
    | '/trips/gokarna_dandeli'
    | '/trips/isha_ooty'
    | '/trips/kallu_falls_harishchandragad'
    | '/trips/ooty_and_coonoor'
    | '/trips/treasures-of-karnataka'
    | '/trips/wayanad'
    | '/blogs/'
    | '/contact/'
    | '/faq/'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  BookingSlugRoute: typeof BookingSlugRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  LegalCancellationRoute: typeof LegalCancellationRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  TripsArunachalam_PondicherryRoute: typeof TripsArunachalam_PondicherryRoute
  TripsArakuRoute: typeof TripsArakuRoute
  TripsGokarna_dandeliRoute: typeof TripsGokarna_dandeliRoute
  TripsIsha_ootyRoute: typeof TripsIsha_ootyRoute
  TripsKallu_falls_harishchandragadRoute: typeof TripsKallu_falls_harishchandragadRoute
  TripsOoty_and_coonoorRoute: typeof TripsOoty_and_coonoorRoute
  TripsTreasuresOfKarnatakaRoute: typeof TripsTreasuresOfKarnatakaRoute
  TripsWayanadRoute: typeof TripsWayanadRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  FaqIndexRoute: typeof FaqIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/wayanad': {
      id: '/trips/wayanad'
      path: '/trips/wayanad'
      fullPath: '/trips/wayanad'
      preLoaderRoute: typeof TripsWayanadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/treasures-of-karnataka': {
      id: '/trips/treasures-of-karnataka'
      path: '/trips/treasures-of-karnataka'
      fullPath: '/trips/treasures-of-karnataka'
      preLoaderRoute: typeof TripsTreasuresOfKarnatakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/ooty_and_coonoor': {
      id: '/trips/ooty_and_coonoor'
      path: '/trips/ooty_and_coonoor'
      fullPath: '/trips/ooty_and_coonoor'
      preLoaderRoute: typeof TripsOoty_and_coonoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/kallu_falls_harishchandragad': {
      id: '/trips/kallu_falls_harishchandragad'
      path: '/trips/kallu_falls_harishchandragad'
      fullPath: '/trips/kallu_falls_harishchandragad'
      preLoaderRoute: typeof TripsKallu_falls_harishchandragadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/isha_ooty': {
      id: '/trips/isha_ooty'
      path: '/trips/isha_ooty'
      fullPath: '/trips/isha_ooty'
      preLoaderRoute: typeof TripsIsha_ootyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/gokarna_dandeli': {
      id: '/trips/gokarna_dandeli'
      path: '/trips/gokarna_dandeli'
      fullPath: '/trips/gokarna_dandeli'
      preLoaderRoute: typeof TripsGokarna_dandeliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/araku': {
      id: '/trips/araku'
      path: '/trips/araku'
      fullPath: '/trips/araku'
      preLoaderRoute: typeof TripsArakuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/Arunachalam_Pondicherry': {
      id: '/trips/Arunachalam_Pondicherry'
      path: '/trips/Arunachalam_Pondicherry'
      fullPath: '/trips/Arunachalam_Pondicherry'
      preLoaderRoute: typeof TripsArunachalam_PondicherryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cancellation': {
      id: '/legal/cancellation'
      path: '/legal/cancellation'
      fullPath: '/legal/cancellation'
      preLoaderRoute: typeof LegalCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation': {
      id: '/booking/confirmation'
      path: '/booking/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$slug': {
      id: '/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/booking/$slug'
      preLoaderRoute: typeof BookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  BookingSlugRoute: BookingSlugRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  LegalCancellationRoute: LegalCancellationRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  TripsArunachalam_PondicherryRoute: TripsArunachalam_PondicherryRoute,
  TripsArakuRoute: TripsArakuRoute,
  TripsGokarna_dandeliRoute: TripsGokarna_dandeliRoute,
  TripsIsha_ootyRoute: TripsIsha_ootyRoute,
  TripsKallu_falls_harishchandragadRoute:
    TripsKallu_falls_harishchandragadRoute,
  TripsOoty_and_coonoorRoute: TripsOoty_and_coonoorRoute,
  TripsTreasuresOfKarnatakaRoute: TripsTreasuresOfKarnatakaRoute,
  TripsWayanadRoute: TripsWayanadRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  FaqIndexRoute: FaqIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
